apiVersion: v1
kind: ConfigMap
metadata:
  name: meridian-app-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "meridian-app.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ index .Values.env "LOG_LEVEL" | default "INFO" | quote }}
  APP_VERSION: {{ .Chart.AppVersion | quote }}
